# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9186f929398f9ca36c4b23e0d548665918798f7d9aa14d112d2e57006033318f6e647b1553ee1be113bc3670e816b9018f26fcf34b4cdcef469d1be41bb37986

test:
  secret_key_base: 879a0e76a0ed970814a1a63d3c471b3a8c96995714b83877e2d433043126baeffdc0abe79e656f147f132b86b75b83df301a10e3679c09df7620d8b686ae5809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
